# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailout',
            name='switch',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bailout',
            name='vote_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bailout',
            name='vote_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
