# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0004_auto_20160923_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='switch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='vote_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='vote_2',
            field=models.IntegerField(),
        ),
    ]
