# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0005_auto_20160923_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='PAC',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='identifier',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='switch',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='vote_1',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='vote_2',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
