# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0006_auto_20160923_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailout',
            name='bailout_opposition',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bailout',
            name='bailout_support',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bailout',
            name='state',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
