# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0007_auto_20160927_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='bailout_opposition',
            field=models.FloatField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='bailout_support',
            field=models.FloatField(blank=True, max_length=25, null=True),
        ),
    ]
