# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0009_bailout_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailout',
            name='financial_services_committee',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
