# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0010_bailout_financial_services_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='party',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
