# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0011_auto_20161007_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='party',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
