# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0013_auto_20161007_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='switch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bailout',
            name='vote_2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
