# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0016_userprofile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='moc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bailout.Bailout'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bailout.UserProfile'),
            preserve_default=False,
        ),
    ]
