# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0018_auto_20161013_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='political_party',
            field=models.CharField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='moc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailout.Bailout', verbose_name='Member of Congress'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'A STEAMING PILE OF POOPY'), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
