# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0020_auto_20161015_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailout',
            name='ada_score',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bailout',
            name='swing_district',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bailout',
            name='win_margin_06',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
