# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailout', '0021_auto_20161018_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailout',
            name='swing_district',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
